note：		
********		
A system of airplane tickets Selling and Management.				
		 
开发工具 
**********  
code::blocks、markdownpad、sphinx	
   
流程图制作工具		
*****************		
visio以及gliffy		   

开发语言		
***********      
C语言，markdown以及RestructureText文本标记语言       
  
  
程序运行方法
*************
1. 通过访问 https://github.com/AutuanLiu/Ticket; 					
2. 点击页面的右上方的 Download ZIP ，将其下载到本地; 			 
3. 在 code::blocks中新建一个工程，将所有 .c  和 .h 文件添加进去;  将 flight_info.csv 和 guest_info.csv 文件放到当前目录下; 					 	
4. backupdata.csv 文件为备用数据，可以不用理会;					
5. 关于.md文件请使用markdownpad打开，或者notepad打开，查看源码，不影响其阅读;					  
6. 同名的HTML文件，可通过浏览器打开.		
7. 推荐使用  code::blocks ,因为该工程在其上开发，**不保证** VC6.0 可以**正常编译运行		

流程图
*********

.. figure:: /images/FlowChart.png
   :scale: 100

   图1：程序主要功能以及数据传输流程图